
package soap.model;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnhancedFolderAttachmentProcessAsyncIn_SFX", targetNamespace = "http://vwfsag.de/EnhancedFolder/SFX")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnhancedFolderAttachmentProcessAsyncInSFX {


    /**
     * 
     * @param enhancedFolderAttachmentProcessMessage
     */
    @WebMethod(operationName = "EnhancedFolderAttachmentProcessAsyncIn_SFX", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void enhancedFolderAttachmentProcessAsyncInSFX(
        @WebParam(name = "EnhancedFolderAttachmentProcessMessage", targetNamespace = "http://vwfsag.de/EnhancedFolder", partName = "EnhancedFolderAttachmentProcessMessage")
        EnhancedFolderAttachmentProcessMessage enhancedFolderAttachmentProcessMessage);

}
