
package soap.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "EnhancedFolderAttachmentProcessAsyncIn_SFXService",
        targetNamespace = "http://vwfsag.de/EnhancedFolder/SFX",
        wsdlLocation = "file:///Users/sven/Desktop/workspace/Codecentric/reply/20150205-mtom-example/src/main/resources/EnhancedFolderAttachmentProcessAsyncIn_SFX.wsdl")
public class EnhancedFolderAttachmentProcessAsyncInSFXService
        extends Service {

    private final static URL ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_EXCEPTION;
    private final static QName ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_QNAME = new QName("http://vwfsag.de/EnhancedFolder/SFX", "EnhancedFolderAttachmentProcessAsyncIn_SFXService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///Users/sven/Desktop/workspace/Codecentric/reply/20150205-mtom-example/src/main/resources/EnhancedFolderAttachmentProcessAsyncIn_SFX.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_WSDL_LOCATION = url;
        ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_EXCEPTION = e;
    }

    public EnhancedFolderAttachmentProcessAsyncInSFXService() {
        super(__getWsdlLocation(), ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_QNAME);
    }

    public EnhancedFolderAttachmentProcessAsyncInSFXService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_QNAME, features);
    }

    public EnhancedFolderAttachmentProcessAsyncInSFXService(URL wsdlLocation) {
        super(wsdlLocation, ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_QNAME);
    }

    public EnhancedFolderAttachmentProcessAsyncInSFXService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_QNAME, features);
    }

    public EnhancedFolderAttachmentProcessAsyncInSFXService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnhancedFolderAttachmentProcessAsyncInSFXService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns EnhancedFolderAttachmentProcessAsyncInSFX
     */
    @WebEndpoint(name = "EnhancedFolderAttachmentProcessAsyncIn_SFXPort")
    public EnhancedFolderAttachmentProcessAsyncInSFX getEnhancedFolderAttachmentProcessAsyncInSFXPort() {
        return super.getPort(new QName("http://vwfsag.de/EnhancedFolder/SFX", "EnhancedFolderAttachmentProcessAsyncIn_SFXPort"), EnhancedFolderAttachmentProcessAsyncInSFX.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *                 Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns EnhancedFolderAttachmentProcessAsyncInSFX
     */
    @WebEndpoint(name = "EnhancedFolderAttachmentProcessAsyncIn_SFXPort")
    public EnhancedFolderAttachmentProcessAsyncInSFX getEnhancedFolderAttachmentProcessAsyncInSFXPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://vwfsag.de/EnhancedFolder/SFX", "EnhancedFolderAttachmentProcessAsyncIn_SFXPort"), EnhancedFolderAttachmentProcessAsyncInSFX.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_EXCEPTION != null) {
            throw ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_EXCEPTION;
        }
        return ENHANCEDFOLDERATTACHMENTPROCESSASYNCINSFXSERVICE_WSDL_LOCATION;
    }

}
